protocols = [{"code": 0, "keyword": "HOPOPT", "description": "IPv6 Hop-by-Hop Option"},
{"code": 1, "keyword": "ICMP", "description": "Internet Control Message"},
{"code": 2, "keyword": "IGMP", "description": "Internet Group Management"},
{"code": 3, "keyword": "GGP", "description": "Gateway-to-Gateway"},
{"code": 4, "keyword": "IPv4", "description": "IPv4 encapsulation"},
{"code": 5, "keyword": "ST", "description": "Stream"},
{"code": 6, "keyword": "TCP", "description": "Transmission Control"},
{"code": 7, "keyword": "CBT", "description": "CBT"},
{"code": 8, "keyword": "EGP", "description": "Exterior Gateway Protocol"},
{"code": 9, "keyword": "IGP", "description": "any private interior gateway (used by Cisco for their IGRP)"},
{"code": 10, "keyword": "BBN-RCC-MON", "description": "BBN RCC Monitoring"},
{"code": 11, "keyword": "NVP-II", "description": "Network Voice Protocol"},
{"code": 12, "keyword": "PUP", "description": "PUP"},
{"code": 13, "keyword": "ARGUS (deprecated)", "description": "ARGUS"},
{"code": 14, "keyword": "EMCON", "description": "EMCON"},
{"code": 15, "keyword": "XNET", "description": "Cross Net Debugger"},
{"code": 16, "keyword": "CHAOS", "description": "Chaos"},
{"code": 17, "keyword": "UDP", "description": "User Datagram"},
{"code": 18, "keyword": "MUX", "description": "Multiplexing"},
{"code": 19, "keyword": "DCN-MEAS", "description": "DCN Measurement Subsystems"},
{"code": 20, "keyword": "HMP", "description": "Host Monitoring"},
{"code": 21, "keyword": "PRM", "description": "Packet Radio Measurement"},
{"code": 22, "keyword": "XNS-IDP", "description": "XEROX NS IDP"},
{"code": 23, "keyword": "TRUNK-1", "description": "Trunk-1"},
{"code": 24, "keyword": "TRUNK-2", "description": "Trunk-2"},
{"code": 25, "keyword": "LEAF-1", "description": "Leaf-1"},
{"code": 26, "keyword": "LEAF-2", "description": "Leaf-2"},
{"code": 27, "keyword": "RDP", "description": "Reliable Data Protocol"},
{"code": 28, "keyword": "IRTP", "description": "Internet Reliable Transaction"},
{"code": 29, "keyword": "ISO-TP4", "description": "ISO Transport Protocol Class 4"},
{"code": 30, "keyword": "NETBLT", "description": "Bulk Data Transfer Protocol"},
{"code": 31, "keyword": "MFE-NSP", "description": "MFE Network Services Protocol"},
{"code": 32, "keyword": "MERIT-INP", "description": "MERIT Internodal Protocol"},
{"code": 33, "keyword": "DCCP", "description": "Datagram Congestion Control Protocol"},
{"code": 34, "keyword": "3PC", "description": "Third Party Connect Protocol"},
{"code": 35, "keyword": "IDPR", "description": "Inter-Domain Policy Routing Protocol"},
{"code": 36, "keyword": "XTP", "description": "XTP"},
{"code": 37, "keyword": "DDP", "description": "Datagram Delivery Protocol"},
{"code": 38, "keyword": "IDPR-CMTP", "description": "IDPR Control Message Transport Proto"},
{"code": 39, "keyword": "TP++", "description": "TP++ Transport Protocol"},
{"code": 40, "keyword": "IL", "description": "IL Transport Protocol"},
{"code": 41, "keyword": "IPv6", "description": "IPv6 encapsulation"},
{"code": 42, "keyword": "SDRP", "description": "Source Demand Routing Protocol"},
{"code": 43, "keyword": "IPv6-Route", "description": "Routing Header for IPv6"},
{"code": 44, "keyword": "IPv6-Frag", "description": "Fragment Header for IPv6"},
{"code": 45, "keyword": "IDRP", "description": "Inter-Domain Routing Protocol"},
{"code": 46, "keyword": "RSVP", "description": "Reservation Protocol"},
{"code": 47, "keyword": "GRE", "description": "Generic Routing Encapsulation"},
{"code": 48, "keyword": "DSR", "description": "Dynamic Source Routing Protocol"},
{"code": 49, "keyword": "BNA", "description": "BNA"},
{"code": 50, "keyword": "ESP", "description": "Encap Security Payload"},
{"code": 51, "keyword": "AH", "description": "Authentication Header"},
{"code": 52, "keyword": "I-NLSP", "description": "Integrated Net Layer Security  TUBA"},
{"code": 53, "keyword": "SWIPE (deprecated)", "description": "IP with Encryption"},
{"code": 54, "keyword": "NARP", "description": "NBMA Address Resolution Protocol"},
{"code": 55, "keyword": "MOBILE", "description": "IP Mobility"},
{"code": 56, "keyword": "TLSP", "description": "Transport Layer Security Protocol using Kryptonet key management"},
{"code": 57, "keyword": "SKIP", "description": "SKIP"},
{"code": 58, "keyword": "IPv6-ICMP", "description": "ICMP for IPv6"},
{"code": 59, "keyword": "IPv6-NoNxt", "description": "No Next Header for IPv6"},
{"code": 60, "keyword": "IPv6-Opts", "description": "Destination Options for IPv6"},
{"code": 61, "keyword": "", "description": "any host internal protocol"},
{"code": 62, "keyword": "CFTP", "description": "CFTP"},
{"code": 63, "keyword": "", "description": "any local network"},
{"code": 64, "keyword": "SAT-EXPAK", "description": "SATNET and Backroom EXPAK"},
{"code": 65, "keyword": "KRYPTOLAN", "description": "Kryptolan"},
{"code": 66, "keyword": "RVD", "description": "MIT Remote Virtual Disk Protocol"},
{"code": 67, "keyword": "IPPC", "description": "Internet Pluribus Packet Core"},
{"code": 68, "keyword": "", "description": "any distributed file system"},
{"code": 69, "keyword": "SAT-MON", "description": "SATNET Monitoring"},
{"code": 70, "keyword": "VISA", "description": "VISA Protocol"},
{"code": 71, "keyword": "IPCV", "description": "Internet Packet Core Utility"},
{"code": 72, "keyword": "CPNX", "description": "Computer Protocol Network Executive"},
{"code": 73, "keyword": "CPHB", "description": "Computer Protocol Heart Beat"},
{"code": 74, "keyword": "WSN", "description": "Wang Span Network"},
{"code": 75, "keyword": "PVP", "description": "Packet Video Protocol"},
{"code": 76, "keyword": "BR-SAT-MON", "description": "Backroom SATNET Monitoring"},
{"code": 77, "keyword": "SUN-ND", "description": "SUN ND PROTOCOL-Temporary"},
{"code": 78, "keyword": "WB-MON", "description": "WIDEBAND Monitoring"},
{"code": 79, "keyword": "WB-EXPAK", "description": "WIDEBAND EXPAK"},
{"code": 80, "keyword": "ISO-IP", "description": "ISO Internet Protocol"},
{"code": 81, "keyword": "VMTP", "description": "VMTP"},
{"code": 82, "keyword": "SECURE-VMTP", "description": "SECURE-VMTP"},
{"code": 83, "keyword": "VINES", "description": "VINES"},
{"code": 84, "keyword": "TTP", "description": "Transaction Transport Protocol"},
{"code": 84, "keyword": "IPTM", "description": "Internet Protocol Traffic Manager"},
{"code": 85, "keyword": "NSFNET-IGP", "description": "NSFNET-IGP"},
{"code": 86, "keyword": "DGP", "description": "Dissimilar Gateway Protocol"},
{"code": 87, "keyword": "TCF", "description": "TCF"},
{"code": 88, "keyword": "EIGRP", "description": "EIGRP"},
{"code": 89, "keyword": "OSPFIGP", "description": "OSPFIGP"},
{"code": 90, "keyword": "Sprite-RPC", "description": "Sprite RPC Protocol"},
{"code": 91, "keyword": "LARP", "description": "Locus Address Resolution Protocol"},
{"code": 92, "keyword": "MTP", "description": "Multicast Transport Protocol"},
{"code": 93, "keyword": "AX.25", "description": "AX.25 Frames"},
{"code": 94, "keyword": "IPIP", "description": "IP-within-IP Encapsulation Protocol"},
{"code": 95, "keyword": "MICP (deprecated)", "description": "Mobile Internetworking Control Pro."},
{"code": 96, "keyword": "SCC-SP", "description": "Semaphore Communications Sec. Pro."},
{"code": 97, "keyword": "ETHERIP", "description": "Ethernet-within-IP Encapsulation"},
{"code": 98, "keyword": "ENCAP", "description": "Encapsulation Header"},
{"code": 99, "keyword": "", "description": "any private encryption scheme"},
{"code": 100, "keyword": "GMTP", "description": "GMTP"},
{"code": 101, "keyword": "IFMP", "description": "Ipsilon Flow Management Protocol"},
{"code": 102, "keyword": "PNNI", "description": "PNNI over IP"},
{"code": 103, "keyword": "PIM", "description": "Protocol Independent Multicast"},
{"code": 104, "keyword": "ARIS", "description": "ARIS"},
{"code": 105, "keyword": "SCPS", "description": "SCPS"},
{"code": 106, "keyword": "QNX", "description": "QNX"},
{"code": 107, "keyword": "A/N", "description": "Active Networks"},
{"code": 108, "keyword": "IPComp", "description": "IP Payload Compression Protocol"},
{"code": 109, "keyword": "SNP", "description": "Sitara Networks Protocol"},
{"code": 110, "keyword": "Compaq-Peer", "description": "Compaq Peer Protocol"},
{"code": 111, "keyword": "IPX-in-IP", "description": "IPX in IP"},
{"code": 112, "keyword": "VRRP", "description": "Virtual Router Redundancy Protocol"},
{"code": 113, "keyword": "PGM", "description": "PGM Reliable Transport Protocol"},
{"code": 114, "keyword": "", "description": "any 0-hop protocol"},
{"code": 115, "keyword": "L2TP", "description": "Layer Two Tunneling Protocol"},
{"code": 116, "keyword": "DDX", "description": "D-II Data Exchange (DDX)"},
{"code": 117, "keyword": "IATP", "description": "Interactive Agent Transfer Protocol"},
{"code": 118, "keyword": "STP", "description": "Schedule Transfer Protocol"},
{"code": 119, "keyword": "SRP", "description": "SpectraLink Radio Protocol"},
{"code": 120, "keyword": "UTI", "description": "UTI"},
{"code": 121, "keyword": "SMP", "description": "Simple Message Protocol"},
{"code": 122, "keyword": "SM (deprecated)", "description": "Simple Multicast Protocol"},
{"code": 123, "keyword": "PTP", "description": "Performance Transparency Protocol"},
{"code": 124, "keyword": "ISIS over IPv4", "description": ""},
{"code": 125, "keyword": "FIRE", "description": ""},
{"code": 126, "keyword": "CRTP", "description": "Combat Radio Transport Protocol"},
{"code": 127, "keyword": "CRUDP", "description": "Combat Radio User Datagram"},
{"code": 128, "keyword": "SSCOPMCE", "description": ""},
{"code": 129, "keyword": "IPLT", "description": ""},
{"code": 130, "keyword": "SPS", "description": "Secure Packet Shield"},
{"code": 131, "keyword": "PIPE", "description": "Private IP Encapsulation within IP"},
{"code": 132, "keyword": "SCTP", "description": "Stream Control Transmission Protocol"},
{"code": 133, "keyword": "FC", "description": "Fibre Channel"},
{"code": 134, "keyword": "RSVP-E2E-IGNORE", "description": ""},
{"code": 135, "keyword": "Mobility Header", "description": ""},
{"code": 136, "keyword": "UDPLite", "description": ""},
{"code": 137, "keyword": "MPLS-in-IP", "description": ""},
{"code": 138, "keyword": "manet", "description": "MANET Protocols"},
{"code": 139, "keyword": "HIP", "description": "Host Identity Protocol"},
{"code": 140, "keyword": "Shim6", "description": "Shim6 Protocol"},
{"code": 141, "keyword": "WESP", "description": "Wrapped Encapsulating Security Payload"},
{"code": 142, "keyword": "ROHC", "description": "Robust Header Compression"},
{"code": 143, "keyword": "Ethernet", "description": "Ethernet (TEMPORARY - registered 2020-01-31, expires 2021-01-31)"},

{"code": 253, "keyword": "experimentation", "description": "Use for experimentation and testing"},
{"code": 254, "keyword": "experimentation", "description": "Use for experimentation and testing"},
{"code": 255, "keyword": "Reserved", "description": ""}]

unassigned = {"code": 0, "keyword": "Unassigned", "description": "Unassigned"}
protocols = {i["code"]: i for i in protocols}
